"""empty message

Revision ID: 08b4824a6ff5
Revises: d1c12703bbff
Create Date: 2021-08-17 17:56:07.282838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b4824a6ff5'
down_revision = 'd1c12703bbff'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
    op.alter_column(table_name='profile_avatars',
        column_name='id',
        type=sa.String
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
